model = "gpt-5.4"
model_reasoning_effort = "xhigh"
approval_policy  = "never"
sandbox_mode = "danger-full-access"
shell_snapshots = true

[projects."/home/konumaru/Documents/repository/"]
trust_level = "trusted"

[projects."/home/konumaru/Documents/repository/explaza-pw-tas-agent"]
trust_level = "trusted"

[projects."/home/konumaru/Documents/repository/stock-watch-app"]
trust_level = "trusted"

[projects."/home/konumaru/Documents/repository/keiba-ai"]
trust_level = "trusted"

[projects."/home/konumaru/dotfiles"]
trust_level = "trusted"

[projects."/Users/konumaru/Documents/repository"]
trust_level = "trusted"

[projects."/Users/konumaru/dotfiles"]
trust_level = "trusted"

[projects."/Users/konumaru/Documents/repository/explaza-pw-tas-agent"]
trust_level = "trusted"

[mcp_servers.openaiDeveloperDocs]
url = "https://developers.openai.com/mcp"

[mcp_servers.linear]
url = "https://mcp.linear.app/mcp"

[mcp_servers.chrome-devtools]
command = "npx"
args = ["chrome-devtools-mcp@latest"]

[mcp_servers.playwright]
command = "npx"
args = ["@playwright/mcp@latest"]

[mcp_servers.playwright.tools.browser_navigate]
approval_mode = "approve"

[mcp_servers.playwright.tools.browser_fill_form]
approval_mode = "approve"

[mcp_servers.playwright.tools.browser_click]
approval_mode = "approve"

[mcp_servers.playwright.tools.browser_press_key]
approval_mode = "approve"

[mcp_servers.playwright.tools.browser_evaluate]
approval_mode = "approve"

[mcp_servers.playwright.tools.browser_resize]
approval_mode = "approve"

[mcp_servers.playwright.tools.browser_drag]
approval_mode = "approve"

[features]
rmcp_client = true

[sandbox_workspace_write]
network_access = true
