set -g mouse on
set -s copy-command 'pbcopy'

# Panel size adjustment
bind-key -n M-Left resize-pane -L 3
bind-key -n M-Right resize-pane -R 3
bind-key -n M-Up resize-pane -U 3
bind-key -n M-Down resize-pane -D 3
