set -g mouse on
set -s copy-command 'pbcopy'

# Panel size adjustment
bind-key -n M-Left resize-pane -L 3
bind-key -n M-Right resize-pane -R 3
bind-key -n M-Up resize-pane -U 3
bind-key -n M-Down resize-pane -D 3


set -g status on
set -g status-position top
set -g status-left ""
set -g status-right ""
setw -g window-status-format " #I:#W "
setw -g window-status-current-format " #[bold,reverse]#I:#W#[default] "
