[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
merged = '0'
hook_source = '''
call coil398#init#coc#hook_source()
'''


[[plugins]]
repo='scrooloose/nerdtree'
hook_add = '''
let g:NERDTreeChDirMode=2
let g:NERDTreeIgnore=['\.rbc$', '\~$', '\.pyc$', '\.db$', '\.sqlite$', '__pycache__']
let g:NERDTreeSortOrder=['^__\.py$', '\/$', '*', '\.swp$', '\.bak$', '\~$']
let g:NERDTreeShowBookmarks=1
let g:nerdtree_tabs_focus_on_files=1
let g:NERDTreeMapOpenInTabSilent = '<RightMouse>'
let g:NERDTreeWinSize = 50
set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*.pyc,*.db,*.sqlite

nnoremap <silent><C-e> :NERDTreeToggle<CR>
map <C-l> gt
map <C-h> gT
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
set laststatus=2
let g:airline#extensions#branch#enabled = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#wordcount#enabled = 0
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
let g:airline_theme = 'wombat'
'''

# LSP (Language Server Protocol)
[[plugins]]
repo = 'prabirshrestha/vim-lsp'

# LSP settings
[[plugins]]
repo = 'mattn/vim-lsp-settings'

# Auto completion
[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

# Auto completion for LSP
[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

