[[plugins]]
repo = 'cespare/vim-toml'


[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
merged = '0'
hook_source = '''
call coil398#init#coc#hook_source()
'''


[[plugins]]
repo='scrooloose/nerdtree'
hook_add = '''
let g:NERDTreeChDirMode=2
let g:NERDTreeIgnore=['\.rbc$', '\~$', '\.pyc$', '\.db$', '\.sqlite$', '__pycache__']
let g:NERDTreeSortOrder=['^__\.py$', '\/$', '*', '\.swp$', '\.bak$', '\~$']
let g:NERDTreeShowBookmarks=1
let g:nerdtree_tabs_focus_on_files=1
let g:NERDTreeMapOpenInTabSilent = '<RightMouse>'
let g:NERDTreeWinSize = 50
set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*.pyc,*.db,*.sqlite

nnoremap <silent><C-e> :NERDTreeToggle<CR>
map <C-l> gt
map <C-h> gT
'''


[[plugins]]
repo = 'vim-airline/vim-airline'
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
set laststatus=2
let g:airline#extensions#branch#enabled = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#wordcount#enabled = 0
let g:airline#extensions#tabline#buffer_idx_mode = 1
let g:airline#extensions#whitespace#mixed_indent_algo = 1
let g:airline_powerline_fonts = 1
'''


# LSP (Language Server Protocol)
[[plugins]]
repo = 'prabirshrestha/vim-lsp'


# LSP settings
[[plugins]]
repo = 'mattn/vim-lsp-settings'
hook_add = '''
  let g:lsp_settings = {
  \  'pylsp-all': {
  \    'workspace_config': {
  \      'pylsp': {
  \        'configurationSources': ['flake8'],
  \        'plugins': {
  \          'flake8': {
  \            'enabled': 1
  \          },
  \          'mccabe': {
  \            'enabled': 0
  \          },
  \          'pycodestyle': {
  \            'enabled': 0
  \          },
  \          'pyflakes': {
  \            'enabled': 0
  \          },
  \          'pylsp_mypy': {
  \            'enabled': 1
  \          },
  \         'isort': {
  \             'enabled': 1
  \          },
  \        }
  \      }
  \    }
  \  }
  \}

  autocmd BufWritePre <buffer> LspDocumentFormatSync
'''


# LSP-lightline bridge
[[plugins]]
repo = 'halkn/lightline-lsp'


# Customize status line
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = {
  \  'mode_map': {'c': 'NORMAL'},
  \  'active': {
  \    'right': [
  \      [ 'lsp_errors', 'lsp_warnings' ],
  \    ]
  \  },
  \  'component_expand': {
  \    'lsp_warnings': 'lightline_lsp#warnings',
  \    'lsp_errors':   'lightline_lsp#errors',
  \  },
  \  'component_type': {
  \    'lsp_warnings': 'warning',
  \    'lsp_errors':   'errors',
  \  },
  \}
'''

# Auto save
[[plugins]]
repo = 'vim-scripts/vim-auto-save'
hook_add = '''
let g:auto_save = 1
let g:auto_save_in_insert_mode = 0
'''

# Auto completion
[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'


# Auto completion for LSP
[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'


[[plugins]]
repo = 'airblade/vim-gitgutter'


[[plugins]]
repo = 'w0rp/ale'


[[plugins]]
repo = 'jiangmiao/auto-pairs'


[[plugins]]
repo ='machakann/vim-highlightedyank'


# -----
# Markdown
# -----

[[plugins]]
repo = 'godlygeek/tabular'
repo = 'preservim/vim-markdown'
hook_add = '''
let g:vim_markdown_folding_disabled = 1
let g:vim_markdown_new_list_item_indent = 2
'''
